# Generated by Django 5.2.6 on 2025-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('install_date', models.DateTimeField()),
                ('hours_used', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('device_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('air_quality', models.FloatField(blank=True, null=True)),
                ('fan_speed', models.IntegerField(default=0)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='filters.filter')),
            ],
        ),
    ]
